---
language: python
python: "2.7"

os: linux

addons:
  apt:
    packages:
    - python-apt

install:
  - pip install ansible
  - touch ansible.cfg
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

script:

  # Check the role's syntax
  - "ansible-playbook tests/travis-test.yml -i tests/travis-inventory --syntax-check"

  # Run the role with ansible-playbook
  - "ansible-playbook tests/travis-test.yml -i tests/travis-inventory --connection=local"

  # Run the role again to check for idempotence
  - >
    ansible-playbook tests/travis-test.yml -i tests/travis-inventory --connection=local
    #    | grep -q 'changed=0.*failed=0'
    #    && (echo 'Idempotence test: pass' && exit 0)
    #    || (echo 'Idempotence test: fail' && exit 1)

  # Check if vim installed successfully
  - "if [[ ! $(vim --version | grep 8.1) ]]; then echo 'vim did not install successfully'; exit 1; else echo 'vim 8.1 installed successfully!'; fi"
