---
language: python
python: "2.7"

os: linux

install:
  - pip install ansible
  - touch ansible.cfg
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:

  # Check the role's syntax
  - "ansible-playbook tests/travis-test.yml -i tests/travis-inventory --syntax-check"

  # Run the role with ansible-playbook
  - "ansible-playbook tests/travis-test.yml -i tests/travis-test.yml --connection=local --sudo"

  # Check if vim installed successfully
  - "if [[ ! $(vim --version | grep 8.1) ]]; then echo 'vim did not install successfully'; exit 1; else echo 'vim 8.1 installed successfully!'; fi"
