---
# tasks for Debian systems

- name: Ensure the given packages are installed
  apt:
    name: "{{ vim_dependencies }}"
    state: present

- name: Ensure vim 7.4 is not installed (pre-installed with Debian systems)
  apt:
    name: vim
    state: absent
