---
# tasks for Debian systems

- name: install necessary vim packages
  apt:
    name: "{{ vim_dependencies }}"
    state: present

- name: uninstall vim 7.4 (pre-installed with Debian systems)
  apt:
    name: vim
    state: absent
