---
# tasks for RedHat systems

- name: Ensure the epel-release repo is installed
  yum:
    name: epel-release
    state: present

- name: Ensure the necessary vim packages are installed
  yum:
    name: "{{ vim_dependencies }}"
    state: present

- name: Ensure the symlink for xsubpp is created
  file:
    src: /usr/bin/xsubpp
    dest: /usr/share/perl5/ExtUtils/xsubpp
    state: link

- name: Ensure vim 7.4 is not installed
  yum:
    name: vim
    state: absent
