---
# tasks for installing vim from source

- name: get the list of tags
  uri:
    url: https://api.github.com/repos/vim/vim/tags
  register: tags

- name: download the vim tarball
  get_url:
    url: "{{ tags.json[0].tarball_url }}"
    dest: /usr/local/src/vim.tar.gz

- name: untar
  unarchive:
    src: /usr/local/src/vim.tar.gz
    dest: /usr/local/src
    remote_src: yes

- name: change the name of the vim-vim-* directory
  shell: mv /usr/local/src/vim-vim* /usr/local/src/vim
  args:
    creates: /usr/local/src/vim

- name: configure
  command: './configure \
    --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=yes \
    --enable-python3interp=yes \
    --with-python3-config-dir={{ python3_dir }} \
    --enable-perlinterp=yes \
    --enable-luainterp=yes \
    --enable-gui=gtk2 \
    --enable-cscope \
    --prefix=/usr/local'
  args:
    chdir: /usr/local/src/vim
    creates: /usr/local/src/vim/src/auto/config.h

- name: make
  make:
    chdir: /usr/local/src/vim
    params:
      VIMRUNTIMEDIR: /usr/local/share/vim/vim81

- name: install
  make:
    chdir: /usr/local/src/vim
    target: install
