---
# handlers file for ansible-role-vim

# run make && make install only when ./configure has not been run before

- name: make
  make:
    chdir: "{{ vim_src_dir }}"
    params:
      VIMRUNTIMEDIR: "{{ vim_runtime_dir }}"
  listen: install

- name: make install
  make:
    chdir: "{{ vim_src_dir }}"
    target: install
  listen: install
