---
# handlers file for ansible-role-vim

# run make && make install only when ./configure has not been run before

- name: make
  make:
    chdir: /usr/local/src/vim
    params:
      VIMRUNTIMEDIR: /usr/local/share/vim/vim81
  listen: install

- name: install
  make:
    chdir: /usr/local/src/vim
    target: install
  listen: install
